### ISSUE TITLE
ios spotify SDK is not available anymore

### ISSUE THREAD

**Issue by gregorymaertens** [Festify/cordova-spotify-oauth#17]
https://github.com/spotify/ios-sdk/archive/beta-25.tar.gz returns 404.
As a result, the ios plugin install fails.
Spotify deprecated (and removed!) the above snapshot. They ask users to move to the new SDK.

Need either to release the SDK (above) within the plugin (till it's supported/allowed) or implement using the new SDK.

**Comment by NeoLegends** [comment]
Ah nvm, they just moved the repo, the same happened to https://github.com/Festify/cordova-spotify. Fixing this asap.

**Comment by NeoLegends** [comment]
Fix pushed to npm.

**Comment by gregorymaertens** [comment]
thanks!
