### ISSUE TITLE
HTTP status code 500

### ISSUE THREAD

**Issue by simone0893** [Festify/cordova-spotify-oauth#22]
Hello,
when I try to authenticate everything looks fine and I also get redirected to the app but the token exchange function gives back a code 500.
Do you have an idea what could be the issue? I think I configured everything fine...

**Comment by NeoLegends** [comment]
HTTP 500dres can be a lot of things. Can you tell us more about the specific error that occurs? Usually the 500 will be accompanied by a short response message as well.

**Comment by simone0893** [comment]
Sadly the response from the post request is empty and there is also no real error message. It just says 'auth_failed'.

![Bildschirmfoto 2019-04-29 um 16 47 39](https://user-images.githubusercontent.com/19683223/56904459-8f1e1080-6a9e-11e9-977d-8dc4fa01223a.png)

**Comment by NeoLegends** [comment]
Ok can you take a look at the AWS lambda logs and see what‘s there?

Best Regards
Moritz Gunz

**Comment by simone0893** [comment]
I got it working, it was a problem with the redirect uri. So this can be closed, thanks for your help!
