### ISSUE TITLE
Error using Ionic 5 / Cordova 9

### ISSUE THREAD

**Issue by ervomk** [Festify/cordova-spotify-oauth#23]
After installing this plugin and when i try to authorize the user, i get this error in the console:

`ERROR: Method 'getCode:' not defined in Plugin 'SpotifyOAuth'`

This is the swift support version that i use in the project.
`"cordova-plugin-add-swift-support": "2.0.2"`

Any ideas how to solve this?

**Comment by danpastori** [comment]
@ervomk Yea, you had to add a single line of code above the method to notify Objective C: https://github.com/521dimensions/cordova-spotify-oauth/blob/develop/src/ios/SpotifyOAuthPlugin.swift#L15 I need to submit a PR but that worked.

**Comment by ervomk** [comment]
@danpastori It works, thank you very much.
