### ISSUE TITLE
authentication not working on ios in ionic 3

### ISSUE THREAD

**Issue by tarun57** [Festify/cordova-spotify-oauth#26]
I'm using ionic 3 
and i'm using spotify cordova plugin for auth but i am not able to login in spotify.

**Comment by NeoLegends** [comment]
What exactly is the issue?

**Comment by tarun57** [comment]
Issue is when i'm click on spotify login button then the function is call in which config spotify login but in this now i'm not entering in  cordova.plugins.spotifyAuth.authorise() after config.

**Comment by NeoLegends** [comment]
> Issue is when i'm click on spotify login button then the function is call in which config spotify login but in this now i'm not entering in cordova.plugins.spotifyAuth.authorize() after config.

Can you describe this in more detail?

**Comment by tarun57** [comment]
cordova.plugins.spotifyAuth.authorize(config)
        .then(({ accessToken, encryptedRefreshToken, expiresAt }) => {
alert("*******");
}) this function is not giving result in ios but in android its working very well . Here i am working in ionic 3. i do not know  why this  problem occuring in ios  .

**Comment by NeoLegends** [comment]
I think I know the error. I'll release the fix shortly.

**Comment by tarun57** [comment]
@NeoLegends Can you make fix it early actually i have release today . Thanks

**Comment by maritaa** [comment]
Hi. Was the error fixed? We are still deeply experiencing the same error I wrote about in the my reported issue (also closed) that seems to be the same one tarun had. I don't see a new issue released yet. Would be great if you could update us on this.
Peace!
