### ISSUE TITLE
spotify-oauth.min.js missing from release?

### ISSUE THREAD

**Issue by gregorymaertens** [Festify/cordova-spotify-oauth#4]
Hello,

I'm trying to integrate this plugin, but when installing it, I'm getting this error:

`
Running command: MYROOT/plugins/cordova-spotify-oauth/install-ios.sh MYROOT

Error during processing of action! Attempting to revert...
Failed to install 'cordova-spotify-oauth': Error: Uh oh!
ENOENT: no such file or directory, open 'MYROOT/plugins/cordova-spotify-oauth/www/build/spotify-oauth.min.js'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at install (MYROOT/platforms/ios/cordova/lib/plugman/pluginHandlers.js:206:36)
    etc...

Error: Uh oh!
ENOENT: no such file or directory, open 'MYROOT/plugins/cordova-spotify-oauth/www/build/spotify-oauth.min.js'

`

when looking at the release zip file it looks like it's missing there (i.e. www/build/spotify-oauth.min.js missing in the zip)
On TravisCI spotify-oauth.min.js is generated by webpack correctly.

Is the artifact not exported correctly into the archive?

Thanks!

References:
$ cordova --version
7.1.0
$ ionic --version
3.16.0

Fetching version 0.1.7 from this plugin

**Comment by NeoLegends** [comment]
Thanks for the heads up! Fixed in 3c15de6794bd95a7c9a20cf74ad38eac0a3380e9.
