### ISSUE TITLE
Plugin crashes before showing login screen

### ISSUE THREAD

**Issue by andreasseiler** [Festify/cordova-spotify-oauth#9]
Hi there,

I tried to use your plugin and it crashes on Android before the Login screen appears. I entered all the neccesary information. Here is my config -> 

`clientId: "15dd21d1356notmyrealId",
redirectUrl: "http://localhost:3000/callback",
scopes: ["streaming"],
tokenExchangeUrl: "http://mysubdomain.herokuapp.com/swap",
tokenRefreshUrl: "http://mysubdomain.herokuapp.com/refresh",
`

The error I'm getting is `Uncaught (in promise) auth_failed: Received authentication response of invalid type error`

Do you have any idea what the reason might be?

Thanks,
Andi

**Comment by NeoLegends** [comment]
Could you check what passes through your cloud functions and whether they have seen any errors? That error occurs when the plugin sees an invalid type of response (must be „code“ for aufhorization code).

**Comment by andreasseiler** [comment]
Sorry, didn't get it to work ... I decided to implement the OAuth Workflow myself. Thanks anyway.
